### ISSUE TITLE
project uses deprecated karma package

### ISSUE THREAD

**Issue by celeriev** [data-platform-hq/mlflow-oidc-auth#40]
Hello,

Thanks a lot for sharing this plugin. I see the web-ui is relying on the `karma-runner` package which is deprecated and presents some dependabot issues. Is there a plan to move away from karma dependency? 

Thanks

**Comment by kharkevich** [comment]
Hello @celeriev,

We plan to migrate from `karma-runner` to another test runner, but this is not a high priority for us at the moment. The UI part is bundled into a `.whl` package as an SPA application, and we believe that karma-runner has no security impact on the released package.

However, contributions are always welcome! If you'd like to help us address this issue, please feel free to open a PR.

**Comment by celeriev** [comment]
understood, thanks @kharkevich
