### ISSUE TITLE
REST API not working

### ISSUE THREAD

**Issue by LLITiF** [data-platform-hq/mlflow-oidc-auth#41]
Hello. I was running Mlflow in k8s as container builded with Dockerfile: https://github.com/data-platform-hq/mlflow-oidc-auth/issues/33#issuecomment-2339439236
And UI authentification works perfect.

But when I'm trying to use it as REST API - it always fails with strange problem. AUTH URL works, but after login it just redirect to main page with authentication button.

```
Code used to connect:
import mlflow

MLFLOW_TRACKING_USERNAME= "username"
MLFLOW_TRACKING_PASSWORD= "password"
MLFLOW_TRACKING_URI="http://mlflow.path"

mlflow.set_tracking_uri(uri=MLFLOW_TRACKING_URI)
mlflow.set_experiment("test_test_test")

with mlflow.start_run():
    mlflow.log_param("loss_fn", "rmse")
    mlflow.log_metric("loss_fn", 10)
```

And part of error:

```
mlflow.exceptions.MlflowException: API request to endpoint was successful but the response body was not in a valid JSON format. Response body: '<!DOCTYPE html>
<html lang="en-US">

<head>
    <title>Login</title>
    <link rel="stylesheet" href="/oidc/static/style.css">
    <link rel="shortcut icon" href="/oidc/static/favicon.ico">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>

```
I was also tried to skip mlflow auth plugin and run it just with requests into url: mlflow.path/api/2.0/mlflow/users/get and got the same

Tested versions: 
MLFlow 2.16.2 + 2.0.0 OIDC
MLFlow 2.17.0 + 2.0.2 OIDC

**Comment by kharkevich** [comment]
Hello! You need to generate an access key, which will be used instead of your password for API calls. Unfortunately only basic auth is supported for right now in case of programmatic access.

<img width="475" alt="image" src="https://github.com/user-attachments/assets/35f791e5-683a-44c7-9acf-cb041b31bc29">


Please use this key instead of password

```python
import mlflow
from mlflow import log_metric, log_param

tracking_server_url = "https://mlflow.technicaldomain.xyz"
username = "user_name@technicaldomain.xyz"
password = "<put_access_key_here>"

mlflow.set_tracking_uri(tracking_server_url)
mlflow.set_experiment("demo_experiment")

import os
os.environ["MLFLOW_TRACKING_USERNAME"] = username
os.environ["MLFLOW_TRACKING_PASSWORD"] = password

with mlflow.start_run(run_name="demo_run"):
    log_param("param1", 5)
    log_param("param2", "test_param")

    log_metric("metric1", 0.1)
    log_metric("metric2", 0.2)

    print("Experiment data logged successfully!")

```
 
[![asciicast](https://asciinema.org/a/MEQZ8aWL6WLJ5vt8vhOv0tbWm.svg)](https://asciinema.org/a/MEQZ8aWL6WLJ5vt8vhOv0tbWm)
