### ISSUE TITLE
Accept OIDC_GROUP_NAME as a list of groups 

### ISSUE THREAD

**Issue by celeriev** [data-platform-hq/mlflow-oidc-auth#45]
Currently, we need to create a specific group on okta for mlflow users, and one for admin.

In my organization, I have multiple groups and I would prefer to specify multiple okta groups that I consider should have access to the app.

Do you think we could add this as a feature?

**Comment by kharkevich** [comment]
Hello. You can easily solve it on IDP side like that:
generic group for access to the application: OIDC_GROUP_NAME = "mlflow-users"
group for admin access: OIDC_ADMIN_GROUP_NAME = "mlflow-admin"
update default mlflow permissions: DEFAULT_MLFLOW_PERMISSION="NO_PERMISSIONS"
add rest of the group to users with more specific access and configure it here
<img width="838" alt="image" src="https://github.com/user-attachments/assets/41e0b5f9-fa41-4bd9-9673-4aff4fd4d9a7">

please let me know if it works for you
