### ISSUE TITLE
Index.html is missing in last releases

### ISSUE THREAD

**Issue by rovorman** [data-platform-hq/mlflow-oidc-auth#49]
Hello,

discovered that after install last version (2.1.0) via `pip install mlflow-oidc-auth` I've got _404 Not found_ for /oidc/ui path

I've found that **index.html** is missing in `site-packages/mlflow_oidc_auth/ui` folder

Looks like yarn step is not working:

```

export MLFLOW_OIDC_AUTH_VERSION=${1:-0.0.0.dev0} - possible cause

pushd web-ui

yarn install

yarn release

popd

python -m build

```
 
maybe should fix it to ${2:-0.0.0.dev0}?

Thanks in advance!

**Comment by rovorman** [comment]
UPD:

Seems like problem with angular budgets (release.sh):


Build at: 2024-10-29T13:05:54.057Z - Hash: 214b9e1872db98be - Time: 9410ms

Warning: bundle initial exceeded maximum budget. Budget 500.00 kB was not met by 526.11 kB with a total of 1.00 MB.

Error: bundle initial exceeded maximum budget. Budget 1.00 MB was not met by 2.11 kB with a total of 1.00 MB.

error Command failed with exit code 1.

**Comment by lguichard78** [comment]
Hello
I face the same problem : index.html is missing.
Is the file supposed to be created during the package installation (through pip install mlflow-oidc-auth) or do I have to build it by hand with yarn ?
Thanks

**Comment by rovorman** [comment]
> Hello I face the same problem : index.html is missing. Is the file supposed to be created during the package installation (through pip install mlflow-oidc-auth) or do I have to build it by hand with yarn ? Thanks

Hi! I've built it manually, increased angular budgets at the same time.
Try to clone repo and run release.sh script.

**Comment by kharkevich** [comment]
Hello! By default, this plugin requires only mlflow-skinny package (check [the installation](https://github.com/data-platform-hq/mlflow-oidc-auth?tab=readme-ov-file#installation) for details), to install this plugin with the entire MLFlow you need to install the **full** version: ```python3 -m pip install mlflow-oidc-auth[full]```

If you want to deploy a lightweight version of the tracking server with OIDC auth you can try the following:

```
python3 -m pip install mlflow-oidc-auth
python3 -m pip install --no-deps mlflow
```

Some discussion can be found here: https://github.com/mlflow/mlflow/issues/7997

**Comment by ion-elgreco** [comment]
@kharkevich running into the same issue, index.html is missing so can't get past /oidc/ui page

**Comment by ion-elgreco** [comment]
Actually, all releases since v2.0 are broken, only v1.5 still had the UI index.html there.
