### ISSUE TITLE
FR: Display user identity on web gui

### ISSUE THREAD

**Issue by NeroBlackstone** [data-platform-hq/mlflow-oidc-auth#58]
I hope there will be an interface showing user identity after logging in: administrator user / common user.

Thanks to the developer of this project!
If I have time, I will check how to implement it

![image](https://github.com/user-attachments/assets/a65bfca6-0ad1-4a0a-ad25-13f28d551e4a)

**Comment by mshodge** [comment]
Hi @NeroBlackstone this could be achieved with a small number of tweaks of the code as shown below. But not sure it's worth adding a PR just yet, so will show how I did it below.

![Uploading Screenshot 2024-12-12 at 14.43.02.png…]()

Line 17 in `web-ui/src/app/shared/components/header/header.component.html` to:

```html
        <span class="pe-1 ms-auto fs-16">
            Hello, {{name}}
            <ng-container *ngIf="admin">(Admin)</ng-container>
        </span>
```

Add this under Line 9 of `web-ui/src/app/shared/components/header/header.component.ts`:

```typescript
  @Input() admin: boolean = false;
```

Change this at the top of `web-ui/src/app/app.component.html`:

```html
    <ml-header 
      [name]="user.display_name"
      [admin]="user.is_admin">
    </ml-header>
```

That should then display (Admin) after the name if the user is an admin.

**Comment by NeroBlackstone** [comment]
@mshodge Hi! Amazing job! Thanks for your guide.

> But not sure it's worth adding a PR just yet
Maybe wait for the main maintainer's decision (of course it would be great if this feature is added)

**Comment by kharkevich** [comment]
Hi @mshodge, please go ahead with PR, I like your idea

**Comment by mshodge** [comment]
PR here: https://github.com/data-platform-hq/mlflow-oidc-auth/pull/59
